### ISSUE TITLE
Matching yara rule

### ISSUE THREAD

**Issue by stuhli** [DCSO/spyre#1]
Hi hillu,

it might be useful to get the information in the log which yara rule matched. Also it might be helpful to get the calling commandline at beginning of the log so you can reconstruct what you have done before (not sure about that)?

The shown hostname is not necasserarily the same host, which is analyzed. If I scan a mounted folder/partition an optional switch for giving the hostname might be useful.

Thx

**Comment by hillu** [comment]
oops, the infrastructure for outputting more information about YARA rules is there, I just forgot to wire it together in the output.
