### ISSUE TITLE
Allow setting command-line options from config file within appended zip

### ISSUE THREAD

**Issue by hw8665** [DCSO/spyre#4]
It would be very useful for some cases if the command-line config could be included in config.Fs as a simple file so that everything could be wrapped up into a single binary that doesn't require setting any custom flags to run.

Ideally, the config would be overwritten by any command-line config flags.

This would allow for someone doing IR to compile a single file that would have any custom settings and yara rules built into it so that all that needs to be done is for the file to be run on any suspected vulnerable host. Where the hosts are managed by other organisations, it may be difficult for the IR team to ensure that flags are correctly set.

**Comment by hillu** [comment]
I am actually working on that.
