### ISSUE TITLE
--report doesn't accept format option

### ISSUE THREAD

**Issue by hw8665** [DCSO/spyre#6]
I don't think that the --report flag works correctly

I think that, in order to create a TSJSON output file called 'log.json' it is supposed to be used like:

--report='log.json;format=tsjson'

but this isn't the case - this creates 2 log files called 'log.json' and 'format=tsjson'.

I believe the problem is that the simpleStringSlice in config.go is splitting the flag into 2 parts before it gets to target.go which tries to do the same thing - it is therefore impossible currently to set the output to be in the TSJSON format. My tiny patch is to change line 30 of target.go to use "@" as the delimiter for format, rather than ";".

Just as a side note, using ";" as a command-line delimiter adds an additional layer of complexity since it's usually a shell command delimiter so bash reads "spyre -r log.json;format=json" as "spyre -r log.json" and "format=json" - "@" is much easier to use. And "," would be an easier delimiter for multiple report files too.

**Comment by hillu** [comment]
You are right. I seem to gotten the separators for `simpleStringSlice` and the target specification in f1d31260dadebde822ef40d65cbb5fc0b4b94ccf mixed up. :-/.

Thanks for spotting!
